spring:
  application:
    name: store
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/STORE?createDatabaseIfNotExist=true
    username: pdbadmin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    locations: classpath:db/migration/{vendor}
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD,EUR,GBP
payment-gateway: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761

# https://dev.to/kpldvnpne/how-to-enable-debug-logs-in-flyway-2b0g
logging:
  level:
    org:
      flywaydb: DEBUG
    db:
      migration: DEBUG