spring:
  application:
    name: store
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/STORE
    username: pdbadmin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    locations: classpath:db/migration/{vendor}
  jpa:
    show-sql: true

# https://dev.to/kpldvnpne/how-to-enable-debug-logs-in-flyway-2b0g
logging:
  level:
    org:
      flywaydb: DEBUG
    db:
      migration: DEBUG